def palindrome_tester(s:str):
    length = len(s)
    for i in range(length // 2):
        if s[i] != s[(-1 * i) - 1]:
            return False
    return True


# NOTE: The below test cases were generated by ChatGPT. The above code was written entirly by Michael Mihailov and passes all test cases!
print(palindrome_tester(""))           # True   - empty string
print(palindrome_tester("a"))          # True   - single character
print(palindrome_tester("aa"))         # True   - two identical characters
print(palindrome_tester("ab"))         # False  - two different characters
print(palindrome_tester("racecar"))    # True   - odd-length palindrome
print(palindrome_tester("abba"))       # True   - even-length palindrome
print(palindrome_tester("abcdef"))     # False  - ordinary non-palindrome
