def compare_tuples(tuple1:tuple, tuple2:tuple):
    def compare_tuples_at_index(tuple1:tuple, tuple2:tuple, index:int):
        if (len(tuple1) <= index or len(tuple2) <= index):
            if (len(tuple1) > len(tuple2)):
                return 1
            if (len(tuple1) < len(tuple2)):
                return -1
            return 0
        if (tuple1[index] > tuple2[index]):
            return 1
        if (tuple1[index] < tuple2[index]):
            return -1
        return compare_tuples_at_index(tuple1, tuple2, index+1)

    return compare_tuples_at_index(tuple1, tuple2, 0)

def lex_insert(L:list, a:int, b:int):
    tup = (a, b)

    for index in range(len(L)):
        compare_val = compare_tuples(tup, L[index])
        if compare_val <= 0:
            L.insert(index, tup)
            return L

    L.append(tup)
    return L


# NOTE: The below test cases were generated by ChatGPT. The above code was written entirly by Michael Mihailov and passes all test cases!
# Empty list
L = []
lex_insert(L, 3, 4)
print(L)  # Correct: [(3, 4)]

# Insert at the beginning
L = [(3, 4), (5, 2), (8, 1)]
lex_insert(L, 1, 10)
print(L)  # Correct: [(1, 10), (3, 4), (5, 2), (8, 1)]

# Insert at the end
L = [(1, 10), (3, 4), (5, 2)]
lex_insert(L, 8, 1)
print(L)  # Correct: [(1, 10), (3, 4), (5, 2), (8, 1)]

# Insert in the middle
L = [(1, 10), (3, 4), (8, 1)]
lex_insert(L, 5, 2)
print(L)  # Correct: [(1, 10), (3, 4), (5, 2), (8, 1)]

# Same first value, smaller second value
L = [(3, 2), (3, 5), (4, 1)]
lex_insert(L, 3, 1)
print(L)  # Correct: [(3, 1), (3, 2), (3, 5), (4, 1)]

# Same first value, larger second value
L = [(3, 1), (3, 2), (4, 1)]
lex_insert(L, 3, 5)
print(L)  # Correct: [(3, 1), (3, 2), (3, 5), (4, 1)]

# Duplicate tuple
L = [(1, 2), (3, 4), (5, 6)]
lex_insert(L, 3, 4)
print(L)  # Correct: [(1, 2), (3, 4), (3, 4), (5, 6)]

# All elements have the same first value
L = [(2, 1), (2, 3), (2, 5)]
lex_insert(L, 2, 4)
print(L)  # Correct: [(2, 1), (2, 3), (2, 4), (2, 5)]

# Negative values
L = [(-5, 2), (-2, 4), (3, 1)]
lex_insert(L, -3, 10)
print(L)  # Correct: [(-5, 2), (-3, 10), (-2, 4), (3, 1)]

# Negative values with same first value
L = [(-3, -5), (-3, 2), (1, 4)]
lex_insert(L, -3, -10)
print(L)  # Correct: [(-3, -10), (-3, -5), (-3, 2), (1, 4)]

# Insert before a tuple with a larger first value
L = [(2, 5), (4, 1), (6, 3)]
lex_insert(L, 4, 0)
print(L)  # Correct: [(2, 5), (4, 0), (4, 1), (6, 3)]
